name: "Validate"

on:
  schedule:
    - cron:  "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  validate:
    uses: "jchonig/ha_cyberq/.github/workflows/validate_sub.yml@main"
